### ISSUE TITLE
Last Message of helathcheck would be nice

### ISSUE THREAD

**Issue by StefanWetterActiware** [bcicen/ctop#226]
Hi,
at the moment on can see "unhealthy" in list view and in single view. It would be nice to get the last message of the unsuccessful healthcheck in singleview (like for example portainer does)
Best regards!

**Comment by stokito** [comment]
Health check doesn’t have a message itself. It simply determined by exit code 0 or 1. Do you mean a last message from logs? Please add a screenshot of portainer.

**Comment by StefanWetterActiware** [comment]
My healthcheck looks like that:
`timeout 10 /eloentryscripts/0001_wait-for-postgres.sh || (echo "DB nicht erreichbar!" && exit 1)`

If i check a unhealthy container:
`docker inspect 922b3924c313 | jq .[0].State.Health`

Output:
> {
>   "Status": "starting",
>   "FailingStreak": 1,
>   "Log": [
>     {
>       "Start": "2020-11-19T16:29:16.792429027+01:00",
>       "End": "2020-11-19T16:29:18.54737082+01:00",
>       "ExitCode": 0,
>       "Output": ""
>     },
>     {
>       "Start": "2020-11-19T16:32:18.558380231+01:00",
>       "End": "2020-11-19T16:32:48.25786516+01:00",
>       "ExitCode": 1,
>       "Output": "DB nicht erreichbar!\npsql: could not translate host name \"elopsql\" to address: Temporary failure in name resolution\nam-Plugin läuft nicht korrekt\n"
>     }
>   ]
> }

I think healthchecks are done in a specific session, so that their (last) output to stdout can be read.

**Comment by stokito** [comment]
Thank you, I didn't know about such functionality. It's described [here](https://docs.docker.com/engine/reference/builder/#healthcheck):
> To help debug failing probes, any output text (UTF-8 encoded) that the command writes on stdout or stderr will be stored in the health status and can be queried with docker inspect. Such output should be kept short (only the first 4096 bytes are stored currently).


To debug this I created the `docker-compose.yaml` with two containers that will change health status each half minute:

```yaml
version: "3.7"
services:
  serv:
    image: "redis:alpine"
    healthcheck:
      test: "test `date +%S` -gt 30 || (echo failed && exit 1)"
      interval: 2s
  core:
    image: "redis:alpine"
    healthcheck:
      test: "test `date +%S` -lt 30 || (echo failed && exit 1)"
      interval: 2s
```

The problem here is that currently health status is received from `health_status` event and it doesn't contains the log. The same is for `exec_die` event: it has `exitCode` attribute but doesn't have the error message. So the only option is to inspect container.
We can't inspect the container each time when it's unhealthy because this may be overkill for performance. But yes, previously it worked in this manner before 4c280ce
I think that the proper solution will be to call inspect before opening Single View
