### ISSUE TITLE
Fixed display size in case of longer names makes output unreadable

### ISSUE THREAD

**Issue by marcinbojko** [bcicen/ctop#228]
When running ctop 0.7.5 when names of containers are longer it seems it's artificially fixed to some value.
All names look the same:
![image](https://user-images.githubusercontent.com/4726723/99365295-5ed3d800-28b7-11eb-8c45-758af5f954fc.png)

**Comment by bcicen** [comment]
can you verify the build version (`ctop -v`) and platform? I'm unable to replicate this in the latest release.

**Comment by marcinbojko** [comment]
@bcicen 
I am terribly sorry, I have an ansible playbook that dowloads latest version
```yaml
      get_url:
        url: https://github.com/bcicen/ctop/releases/download/v0.7.5/ctop-0.7.5-linux-amd64
        dest: /usr/local/bin/ctop
        mode: "755"
        checksum: sha256:https://github.com/bcicen/ctop/releases/download/v0.7.5/sha256sums.txt
```
For some reason version was not replaced and I/ve stuck with 0.7.4
With 0.7.5 everything works as expected
